### ISSUE TITLE
plugin not on packagist yet

### ISSUE THREAD

**Issue by bnomei** [fabianmichael/kirby-multi-toggle-field#1]
can not install with composer

**Comment by fabianmichael** [comment]
@bnomei This plugin was never meant to be an official release. @bastianallgeier said, that he probably wants to include bring it into core at some point. I don’t know when this will happen, but if it will take longer, I could probably look into how to publish it there.

**Comment by fabianmichael** [comment]
@bnomei Just added this to packagist. :-)

**Comment by bastianallgeier** [comment]
Argh, it's one of those things that totally fall behind the cupboard at some point. I'm sorry :(
