### ISSUE TITLE
Custom icons?

### ISSUE THREAD

**Issue by owzim** [fabianmichael/kirby-multi-toggle-field#3]
Is it possible to have custom icons or only kirby icons? Since in the example gif there are those layout icons, which are not part of the standard kirby icons.

**Comment by fabianmichael** [comment]
@owzim Yes, but you need to set up a panel extension to register your custom icons. See the Kirby reference: https://getkirby.com/docs/reference/plugins/extensions/icons

BTW, Kirby uses the Nucleo icon set (https://nucleoapp.com/).
